import Head from "next/head";
import Link from "next/link";
import { NavBar } from "@/components/nav-bar";

export default function Home() {
  return (
    <>
      <Head>
        <title>evoly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <main className="px-8 lg:px-16 text-center flex flex-col text-white items-center justify-center bg-gradient-to-br from-neutral-600 via-teal-900  to-cyan-700 h-screen">
        <h1 className="hero-text--title font-mono font-bold text-center text-4xl sm:text-5xl md:text-6xl lg:text-7xl">
          Seamless waste collection.
        </h1>
        <h2 className="hero-text--header font-mono mt-6 tracking-widest text-3xl sm:text-4xl md:text-5xl lg:text-6xl">
          Zero upfront investment
        </h2>
        <div className="cta flex flex-col items-center">
          <h3 className="mt-6 text-white text-xl lg:text-2xl">
            Our <span className="font-bold">Pay as you go</span> model adapts to
            you.
          </h3>
          <div className="flex space-x-4">
            <Link
              className="w-fit mt-6 px-8 py-2 bg-teal-500 hover:bg-blue-700 transition-colors font-semibold rounded-md hover:shadow-md"
              href="/demo"
            >
              Book a demo
            </Link>
            <Link
              className="w-fit mt-6 px-8 py-2 border-2 border-teal-500  hover:bg-teal-700 transition-colors font-semibold rounded-md hover:shadow-md"
              href="/map"
            >
              See our map of sensors
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
